CREATE TABLE "##"."DAT_PROCESS" 
   ("PROCESSID" int NOT NULL,
    "WORKITEMID" nvarchar2(20) NOT NULL, 
    "TEMPLATEID" nvarchar2(20), 
    "LASTUPDATETIME" nchar(50),
     PRIMARY KEY (PROCESSID,WORKITEMID)
   );
   
   
   CREATE TABLE "##"."DAT_WORKITEM" 
   ("WORKITEMID" nvarchar2(20)NOT NULL, 
    "TASKID" nvarchar2(20)NOT NULL, 
    "TEMPLATEID" nvarchar2(20)NOT NULL, 
    "LASTHISTORYNO" int NOT NULL,
    "LASTUPDATETIME" nchar(50),
    PRIMARY KEY (WORKITEMID)
   );
   
   CREATE TABLE "##"."DAT_FOLDERITEM" 
   ("WORKITEMID" nvarchar2(20) NOT NULL, 
    "FOLDERITEMNO" int NOT NULL, 
    "TEMPLATEID" nvarchar2(20) NOT NULL, 
    "LASTUPDATETIME" nchar(50), 
    PRIMARY KEY (WORKITEMID,FOLDERITEMNO)
   );
   
   CREATE TABLE "##"."DAT_DOCUMENT" 
   ("WORKITEMID" nvarchar2(20) NOT NULL, 
    "FOLDERITEMNO" int NOT NULL, 
    "DOCUMENTNO" int NOT NULL,
    "TEMPLATEID" nvarchar2(20) NOT NULL, 
    "PAGECOUNT" int NOT NULL,
    "VIEWINFORMATION" nvarchar2(2000),
    "DOCUMENTTYPE" int,
    "LASTUPDATETIME" nchar(50),
    CONSTRAINT "ENSURE_JSON1" CHECK (VIEWINFORMATION IS JSON) ENABLE,
    PRIMARY KEY (WORKITEMID,FOLDERITEMNO,DOCUMENTNO)
   );
   
   CREATE TABLE "##"."DAT_LAYER" 
   ("WORKITEMID" nvarchar2(20) NOT NULL, 
    "FOLDERITEMNO" int NOT NULL, 
    "DOCUMENTNO" int NOT NULL,
    "LAYERNO" int NOT NULL,
    "TEMPLATEID" nvarchar2(20) NOT NULL, 
    "OWNERID" nvarchar2(20) NOT NULL,
    "ANNOTATIONS" nvarchar2(2000),
    "LASTUPDATETIME" nchar(50),
    CONSTRAINT "ENSURE_JSON2" CHECK (ANNOTATIONS IS JSON) ENABLE,
    PRIMARY KEY (WORKITEMID,FOLDERITEMNO,DOCUMENTNO,LAYERNO)
   );
   
    CREATE TABLE "##"."STR_DATA_FILE" 
   ("WORKITEMID" nvarchar2(20) NOT NULL, 
    "FOLDERITEMNO" int NOT NULL, 
    "DOCUMENTNO" int NOT NULL,
    "DOCUMENTDATAPATH" nvarchar2(260), 
    "LASTUPDATETIME" nchar(50),
    PRIMARY KEY (WORKITEMID,FOLDERITEMNO,DOCUMENTNO)
   );
   
    CREATE TABLE "##"."STR_LOG_ACCESS" 
   ("EVENTID" nvarchar2(20) NOT NULL, 
    "PROCESSTIME" nchar(50) NOT NULL, 
    "USERID" nvarchar2(255) NOT NULL,
    "WORKITEMID" nvarchar2(20) NOT NULL, 
    "HISTORYNO" int NOT NULL,
    "PROCESSID"int NOT NULL,
    "PROCESSVERSION"float,
    "TASKID" nvarchar2(20) NOT NULL,
    "LASTUPDATETIME" nchar(50),
    PRIMARY KEY (EVENTID)
   );
   
   CREATE TABLE "##"."CTL_EVENT" 
   ("EVENTID" nvarchar2(20) NOT NULL, 
    "USERID" nvarchar2(20) NOT NULL, 
    "WORKITEMID" nvarchar2(20) NOT NULL,
    "STATUS" nvarchar2(20), 
    "TASKID" nvarchar2(20) NOT NULL,
    "WORKITEMDATA"nvarchar2(2000),
    "LASTUPDATETIME" nchar(50),
    CONSTRAINT "ENSURE_JSON3" CHECK (WORKITEMDATA IS JSON) ENABLE,
    PRIMARY KEY (EVENTID)
   );
   
   CREATE TABLE "##"."CTL_TEMPLATE" 
   ("USERID" nvarchar2(255) NOT NULL, 
    "TEMPLATEID" nvarchar2(20) NOT NULL, 
    "ACCESSAUTHORITY" int,
    "LASTUPDATETIME" nchar(50),
    PRIMARY KEY (USERID,TEMPLATEID)
   );
   
   CREATE TABLE "##"."MGR_TEMPLATE_P" 
   ("PROFILEID" nvarchar2(255) NOT NULL, 
    "TEMPLATEID" nvarchar2(20) NOT NULL, 
    "ACCESSAUTHORITY" int,
    "LASTUPDATETIME" nchar(50),
    PRIMARY KEY (PROFILEID,TEMPLATEID)
   );
   
   CREATE TABLE "##"."MGR_TEMPLATE_U" 
   ("USERID" nvarchar2(255) NOT NULL, 
    "TEMPLATEID" nvarchar2(20) NOT NULL, 
    "ACCESSAUTHORITY" int,
    "LASTUPDATETIME" nchar(50),
    PRIMARY KEY (USERID,TEMPLATEID)
   );
   
   CREATE TABLE "##"."MGR_PROCESS" 
   ("PROCESSID" int NOT NULL, 
    "PROCESSNAME" nvarchar2(255), 
    "PROCESSVERSION" float,
    "DESCRIPTION" nvarchar2(255),
    "PROCESSDEFINITION"nvarchar2(2000),
    "DOCUMENTDATASAVEPATH" nvarchar2(260),
    "LASTUPDATETIME" nchar(50),
    CONSTRAINT "ENSURE_JSON4" CHECK (PROCESSDEFINITION IS JSON) ENABLE,
    PRIMARY KEY (PROCESSID)
   );
   
    CREATE TABLE "##"."MGR_PROCESS_SERVICE" 
   ("PROCESSISERVICEID" int NOT NULL, 
    "WORKSPACEID" int NOT NULL, 
    "PROCESSISERVICENAME" nvarchar2(255),
    "LASTUPDATETIME" nchar(50),
    PRIMARY KEY (PROCESSISERVICEID)
   );
   
    CREATE TABLE "##"."MGR_TEMPLATE" 
   ("TEMPLATEID" nvarchar2(20) NOT NULL, 
    "TEMPLATENAME" nvarchar2(255), 
    "TEMPLATETABLENAME" nvarchar2(255),
    "TEMPLATEFIELD" nvarchar2(2000),
    "TEMPLATETYPE"nvarchar2(255),
    "LASTUPDATETIME" nchar(50),
    CONSTRAINT "ENSURE_JSON5" CHECK (TEMPLATEFIELD IS JSON) ENABLE,
    PRIMARY KEY (TEMPLATEID)
   );
   
   CREATE TABLE "##"."MGR_SCHEDULE" 
   ("SCHEDULEID" int NOT NULL, 
    "HOSTNAME" nvarchar2(255), 
    "PROCESSID" int NOT NULL,
    "PROCESSISERVICEID" int,
    "TASKID" nvarchar2(20) NOT NULL,
    "STARTTIME" nchar(50),
    "ENDTIME" nchar(50),
    "ENABLE_DISABLE" nvarchar2(20),
    "NEXTRUNDATE"nchar(50),
    "RUNINTERVALDAY"nvarchar2(8),
    "RUNINTERVALHOUR" nvarchar2(2),
    "RUNINTERVALMINUTE" nchar(50),
    "RUNINTERVALSECOND" nchar(50),
    "LASTUPDATETIME" nchar(50),
    PRIMARY KEY (SCHEDULEID)
   )
