-- Updated by データベース設計書_V0.92.xls

CREATE TABLE DAT_PROCESS 
   (PROCESSID int NOT NULL,
    WORKITEMID nvarchar(20) NOT NULL, 
    TEMPLATEID nvarchar(20), 
    LASTUPDATETIME nvarchar(17),
     PRIMARY KEY (PROCESSID,WORKITEMID)
   );
   
   
   CREATE TABLE DAT_WORKITEM 
   (WORKITEMID nvarchar(20)NOT NULL, 
    TASKID nvarchar(20)NOT NULL, 
    TEMPLATEID nvarchar(20), 
    LASTHISTORYNO int NOT NULL,
    LASTUPDATETIME nvarchar(17),
    PRIMARY KEY (WORKITEMID)
   );
   
   CREATE TABLE DAT_FOLDERITEM 
   (WORKITEMID nvarchar(20) NOT NULL, 
    FOLDERITEMNO int NOT NULL, 
    TEMPLATEID nvarchar(20), 
    LASTUPDATETIME nvarchar(17), 
    PRIMARY KEY (WORKITEMID,FOLDERITEMNO)
   );
   
   CREATE TABLE DAT_DOCUMENT 
   (WORKITEMID nvarchar(20) NOT NULL, 
    FOLDERITEMNO int NOT NULL, 
    DOCUMENTNO int NOT NULL,
    TEMPLATEID nvarchar(20), 
    PAGECOUNT int NOT NULL,
    VIEWINFORMATION nvarchar(MAX),
    DOCUMENTTYPE nvarchar(20),
    LASTUPDATETIME nvarchar(17),
    CONSTRAINT ENSURE_JSON1 CHECK (ISJSON(VIEWINFORMATION)>0),
    PRIMARY KEY (WORKITEMID,FOLDERITEMNO,DOCUMENTNO)
   );
   
   CREATE TABLE DAT_LAYER 
   (WORKITEMID nvarchar(20) NOT NULL, 
    FOLDERITEMNO int NOT NULL, 
    DOCUMENTNO int NOT NULL,
    LAYERNO int NOT NULL,
    LAYERNAME nvarchar(255) NOT NULL,
    TEMPLATEID nvarchar(20), 
    OWNERID nvarchar(255),
    ANNOTATIONS nvarchar(MAX),
    INSERTDATETIME nvarchar(17),
    LASTUPDATETIME nvarchar(17),
    CONSTRAINT ENSURE_JSON2 CHECK (ISJSON(ANNOTATIONS)>0),
    PRIMARY KEY (WORKITEMID,FOLDERITEMNO,DOCUMENTNO,LAYERNO)
   );
   
    CREATE TABLE STR_DATA_FILE 
   (WORKITEMID nvarchar(20) NOT NULL, 
    FOLDERITEMNO int NOT NULL, 
    DOCUMENTNO int NOT NULL,
    DOCUMENTDATAPATH nvarchar(260), 
    LASTUPDATETIME nvarchar(17),
    PRIMARY KEY (WORKITEMID,FOLDERITEMNO,DOCUMENTNO)
   );
   
    CREATE TABLE STR_DATA_DB 
   (WORKITEMID nvarchar(20) NOT NULL, 
    FOLDERITEMNO int NOT NULL, 
    DOCUMENTNO int NOT NULL,
    DOCUMENTDATA nvarchar(MAX), 
    LASTUPDATETIME nvarchar(17),
    PRIMARY KEY (WORKITEMID,FOLDERITEMNO,DOCUMENTNO)
   );
   
    CREATE TABLE STR_LOG_ACCESS 
   (EVENTID nvarchar(20) NOT NULL, 
    PROCESSTIME nvarchar(17), 
    USERID nvarchar(255) NOT NULL,
    WORKITEMID nvarchar(20) NOT NULL, 
    HISTORYNO int NOT NULL,
    TASKID nvarchar(20) NOT NULL,
    LASTUPDATETIME nvarchar(17),
    PRIMARY KEY (EVENTID)
   );
   
   CREATE TABLE CTL_EVENT 
   (EVENTID nvarchar(20) NOT NULL, 
    USERID nvarchar(255) NOT NULL, 
    WORKITEMID nvarchar(20) NOT NULL,
    STATUS nvarchar(20), 
    TASKID nvarchar(20) NOT NULL,
    TRANSACTIONTOKEN nvarchar(255),
    WORKITEMDATA nvarchar(MAX),
    LASTUPDATETIME nvarchar(17),
    CONSTRAINT ENSURE_JSON3 CHECK (ISJSON(WORKITEMDATA)>0),
    PRIMARY KEY (EVENTID)
   );
   
   CREATE TABLE CTL_TEMPLATE 
   (USERID nvarchar(255) NOT NULL, 
    TEMPLATEID nvarchar(20) NOT NULL, 
    ACCESSAUTHORITY nvarchar(20),
    LASTUPDATETIME nvarchar(17),
    PRIMARY KEY (USERID,TEMPLATEID)
   );
   
   CREATE TABLE MGR_TEMPLATE_P 
   (PROFILEID nvarchar(255) NOT NULL, 
    TEMPLATEID nvarchar(20) NOT NULL, 
    ACCESSAUTHORITY nvarchar(20),
    LASTUPDATETIME nvarchar(17),
    PRIMARY KEY (PROFILEID,TEMPLATEID)
   );
   
   CREATE TABLE MGR_TEMPLATE_U 
   (USERID nvarchar(255) NOT NULL, 
    TEMPLATEID nvarchar(20) NOT NULL, 
    ACCESSAUTHORITY nvarchar(20),
    LASTUPDATETIME nvarchar(17),
    PRIMARY KEY (USERID,TEMPLATEID)
   );
   
   CREATE TABLE MGR_PROCESS 
   (PROCESSID int NOT NULL, 
    PROCESSNAME nvarchar(255), 
    PROCESSVERSION float,
    DESCRIPTION nvarchar(255),
    PROCESSDEFINITION nvarchar(MAX),
    DOCUMENTDATASAVEPATH nvarchar(260),
    LASTUPDATETIME nvarchar(17),
    CONSTRAINT ENSURE_JSON4 CHECK (ISJSON(PROCESSDEFINITION)>0),
    PRIMARY KEY (PROCESSID)
   );

    CREATE TABLE MGR_TEMPLATE 
   (TEMPLATEID nvarchar(20) NOT NULL, 
    TEMPLATENAME nvarchar(255), 
    TEMPLATETABLENAME nvarchar(255),
    TEMPLATEFIELD nvarchar(MAX),
    TEMPLATETYPE nvarchar(255),
    LASTUPDATETIME nvarchar(17),
    CONSTRAINT ENSURE_JSON5 CHECK (ISJSON(TEMPLATEFIELD)>0),
    PRIMARY KEY (TEMPLATEID)
   );
   
   CREATE TABLE MGR_SCHEDULE 
   (SCHEDULEID int NOT NULL, 
    HOSTNAME nvarchar(255), 
    PROCESSID int NOT NULL,
    PROCESSISERVICEID int,
    TASKID nvarchar(20) NOT NULL,
    STARTTIME nvarchar(17),
    ENDTIME nvarchar(17),
    ENABLE_DISABLE nvarchar(20) NOT NULL,
    NEXTRUNDATE nvarchar(17),
    RUNINTERVALDAY nvarchar(8),
    RUNINTERVALHOUR  nvarchar(2),
    RUNINTERVALMINUTE  nvarchar(2),
    RUNINTERVALSECOND  nvarchar(2),
    LASTUPDATETIME  nvarchar(17),
    PRIMARY KEY (SCHEDULEID)
   );
   
    CREATE TABLE MGR_STRAGE_FILE 
   (PROCESSID int NOT NULL,
    SITEID int NOT NULL, 
    SITEMANAGEMENTTYPE nvarchar(MAX),
    LASTUPDATETIME nvarchar(17),
     CONSTRAINT ENSURE_JSON6 CHECK (ISJSON(SITEMANAGEMENTTYPE)>0),
     PRIMARY KEY (PROCESSID,SITEID)
   );
   
   CREATE TABLE MGR_STRAGE_DB 
   (PROCESSID int NOT NULL,
    SCHEMANAME nvarchar(255) NOT NULL, 
    DBUSER nvarchar(255),
    DBPASSWORD nvarchar(515),
    OWNER nvarchar(255),
    DBSERVER nvarchar(255),
    LASTUPDATETIME nvarchar(17),
     PRIMARY KEY (PROCESSID,SCHEMANAME)
   );
   
   CREATE TABLE MGR_TASK 
   (TASKID nvarchar(20) NOT NULL, 
    TASKNAME nvarchar(255), 
    CUSTOMTASKID nvarchar(20),
    PROCESSID int NOT NULL,
    LASTUPDATETIME nvarchar(17),
    PRIMARY KEY (TASKID,PROCESSID)
   )

